### ISSUE TITLE
get-hvmachine & get-hvmachinesummary maximum 1000 results

### ISSUE THREAD

**Issue by Magneet** [vmware/PowerCLI-Example-Scripts#129]
When I do a get-hvmachine or get-hvmachinesummary from the vmware.hv.helper the maxiimum output count is 1000. This is not enough since pools and complete environments can get way bigger then that. It seems to be caused by the queryservice only giving 1000 results as well.

$hvServer1 = Connect-HVServer -Server CONNECTIONSERVER
$Services1= $hvServer1.ExtensionData
$queryService = New-Object VMware.Hv.QueryServiceService
$defn = New-Object VMware.Hv.QueryDefinition
$defn.limit= 9999
$defn.startingOffset = 20
$defn.maxpagesize = 9999
$defn.queryEntityType = 'MachineNamesView'
$QueryResults = $queryService.queryservice_create($Services1, $defn)
($queryresults.results).count

this always maxes out at 1000 results. If I set the startingoffset to 800 I get 303 results

**Comment by kmruddy** [comment]
Give the module a go. 
[PR130](https://github.com/vmware/PowerCLI-Example-Scripts/pull/130) might help/fix the issue.

**Comment by rpstester** [comment]
#130 and #131 fixed this issue for me. Thank you!
