### ISSUE TITLE
Error Using Set-HVPool to Disable Linked-Clone Pool

### ISSUE THREAD

**Issue by rpstester** [vmware/PowerCLI-Example-Scripts#132]
I am trying to disable provisioning on an automated linked clone pool.  First, I tried something like 
`Set-HVPool -PoolName 'whatever' -stop`
but it gives an error 

> Set-HVPool : Start/Stop operation is not supported for **_Poll_** with name : **_[.DesktopSummaryData.Name]_**

If I use the -Enable or -Disable parameter, then it will not affect the provisioning status.

So I tried setting the key directly:
`Set-HVPool -PoolName 'whatever' -Key 'automatedDesktopData.virtualCenterProvisioningSettings.enableProvisioning' -Value $true`
Enabling works without a problem.

However, if I merely change the Value from $true to $false, then I get two errors:

> Set-HVPool : Both 
> key:[automatedDesktopData.virtualCenterProvisioningSettings.enableProvisioning] and 
> value:[False] needs to be specified

and 

> Exception calling "Desktop_Update" with "3" argument(s): "There is an error in the 
> XML document."
> At \\\\whateverPath\Modules\VMware.Hv.Helper\VMware.HV.Helper.psm1:5913 char:8
> $desktop_helper.Desktop_Update($services,$item,$updates)

So what can be done to set this setting without error so that I can disable provisioning in Horizon View 7.2 with PowerShell?

Please let me know if you need any more information. Thanks!

**Comment by mtelvers** [comment]
Hi, I've updated Set-HVPool in PR #131 to address both your -Stop query and the general issue of setting any key to a $false value.

**Comment by rpstester** [comment]
The -Stop works now. Thank you!
So does the -key and -value. Thank you very much!
