### ISSUE TITLE
Create get-hvuser and/or create assign-hvmachine

### ISSUE THREAD

**Issue by Magneet** [vmware/PowerCLI-Example-Scripts#151]
To entitle a user to a manual machine the advanced option for base.user needs to be set with the base.name value from aduserorgroupsummaryview besides creating the query yourself there's no way to do that now
I have done it manually like this: 
$username="username"
$queryService = New-Object VMware.Hv.QueryServiceService
$defn = New-Object VMware.Hv.QueryDefinition
$defn.queryEntityType = 'ADUserOrGroupSummaryView'
$defn.filter = New-Object VMware.Hv.QueryFilterEquals -property @{'memberName'='base.name'; 'value' = $userName}
try     {
        $userid=($queryService.queryservice_create($Services1, $defn)).results[0].id
        }
catch   { 
        throw "Can't find $Username, exiting" 
        }

and feed that to get-hvmachine -machinename machinename| set-hvmachine -key base.user -Value $userid 

this imho should receive an own command for it, also with get-hvuser all entitlements could be shown over desktops and applications for that user

**Comment by biacz** [comment]
i'd love to see a PR for this

**Comment by mtelvers** [comment]
Hi Magneet, I've added code to PR#165 to modify 'Set-HVMachine' so you can use it like this:

    Set-HVMachine -HvServer $vcs -MachineName machine.fqdn -User "domain\user"

It's not quite what you asked for, but it gets the job done without needing to build your own query
