### ISSUE TITLE
create remove-hvmachine

### ISSUE THREAD

**Issue by Magneet** [vmware/PowerCLI-Example-Scripts#153]
there's a way to add a machine to a manual pool but not a way to remove them (for example to add them to another connection broker) 

this can easily be done like this:
 $services1.desktop.Desktop_RemoveMachineFromManualDesktop((get-hvpool -poolname POOLNAME).id, (get-hvmachine -machinename MACHINENAME).id)

**Comment by admoseley** [comment]
Is there a similar method for removing a machine from an automated full clone pool?

**Comment by freythman** [comment]
The existing function should work for managed machines. Eg.

`Remove-HVMachine -MachineNames "vdidesktop01"`

**Comment by admoseley** [comment]
@freythman I've tried that in the past. That command deletes the VM. I just need the vm removed from the pool, but still reside in Vcenter.

**Comment by freythman** [comment]
If you edit line [10146](https://github.com/vmware/PowerCLI-Example-Scripts/blob/dc191995f3ec3bd9c08963c7913662147403e906/Modules/VMware.Hv.Helper/VMware.HV.Helper.psm1#L10146) to `$deleteSpec.DeleteFromDisk = $false` then your machine(s) won't be deleted.

A more permanent solution would be to include a parameter for `Remove-HVMachine` to toggle this property. That's a pretty easy change. I'll work on that.

**Comment by freythman** [comment]
@admoseley copying my comment from https://github.com/vmware/PowerCLI-Example-Scripts/issues/193

Added -`DeleteFromDisk` to `Remove-HVMachine` in https://github.com/vmware/PowerCLI-Example-Scripts/pull/222

Defaulted to `$true` so to not remove the machine from vSphere you would set it to false `Remove-HVMachine -MachineName 'VMName01' -DeleteFromDisk:$false`

Now we wait for it to be accepted and merged 👍

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/222
