### ISSUE TITLE
error when using new-hvpool I get an error  (Domain administrator (domain.local) and container (dom.domain.nl) refer to different domains)

### ISSUE THREAD

**Issue by cvvcvv** [vmware/PowerCLI-Example-Scripts#168]
New-HVPool -LinkedClone -PoolName testkeespw -PoolDisplayName testkeespw -Description "pool met powercli gemaakt" -UserAssignment FLOATING  -defaultDisplayProtocol BLAST -enableHTMLAccess 1 -Pa
rentVM "MCH-W7-GPU-GIP1.00" -SnapshotVM HW-upgrade -VmFolder testkees -HostOrCluster "cluster 1" -ResourcePool "cluster 1" -Datastores vsanDatastore -UseVSAN 1 -NamingMethod PATTERN -NamingPattern "W7-test-{
n:fixed=1}"  -DomainAdmin sa_view-cp -CustType QUICK_PREP

Domain administrator (domain.local) and container (dom.domain.nl) refer to different domains)

**Comment by mtelvers** [comment]
Hi, what happens if you don't specify -DomainAdmin and/or you do specify -adContainer?

**Comment by cvvcvv** [comment]
Hi, When I specify a no adcontainer and domainadmin I get the same error
when I specify  adcontainer in this format ("OU=Floating GPU,OU=VDI,OU=Windows 7,DC=domain,DC=local") and no domainadmin I get No AdContainer found with name.....
The adcontainer is present in AD.

**Comment by cvvcvv** [comment]
Hi, a Collegae has made a other script,  and use for -domainadmin the UPN format.
This script is working, thanks for the assistance.
