### ISSUE TITLE
VMware.VMC module only lists firts 20 Logical networks

### ISSUE THREAD

**Issue by gertvangorp** [vmware/PowerCLI-Example-Scripts#176]
The Function Get-VMCLogicalNetwork
 os calling the VMC service as described below.

    $logicalNetworkService = Get-VmcService com.vmware.vmc.orgs.sddcs.networks.logical

in the GUI we see  more then 20 logical networks available.  The above only results in a table of only the 20 first created networks.

![2018-03-12_18-58-35](https://user-images.githubusercontent.com/31863524/37300990-a681b2ac-2627-11e8-9010-e819ad8a1bb2.png)
![2018-03-12_18-58-19](https://user-images.githubusercontent.com/31863524/37300991-a6af0a7c-2627-11e8-86fc-3f5c5f755b0d.png)
gert

**Comment by lucdekens** [comment]
Should be fixed with https://github.com/vmware/PowerCLI-Example-Scripts/pull/235

**Comment by kamennikolov** [comment]
Fixed in https://github.com/vmware/PowerCLI-Example-Scripts/pull/235
