### ISSUE TITLE
Run cmdlet against multiple $hvServers at once

### ISSUE THREAD

**Issue by biacz** [vmware/PowerCLI-Example-Scripts#178]
Hey guys, 

we are oftenly running queries against multiple environments.
For example we have a script that should run set-hvmachine -machinename $vm -maintenance ENTER_MAINTENANCE_MODE against all servers in $hvServer.

Now i see that in one of the lines it does this: 
**$machines = get-hvmachinesummary -machinename $machinename -suppressinfo $true -hvserver $hvServer** which basically only uses $hvServer[0] 

Is there an easy fix to run this against all servers that are connected?
I am not good enough to hack this myself, maybe someone else found a solution already.

Thanks!

**Comment by freythman** [comment]
When you connect to multiple Connection Servers, an object, `$global:DefaultHVServers` is created that contains each one of them. For example:

`Connect-HVServer -Server 'hvserver01.domain.com'`
`Connect-HVServer -Server 'hvserver02.domain.com'`

`$machines = @()`
`ForEach ($HVServer in $global:DefaultHVServers) {`
     `$machines += get-hvmachinesummary -machinename $machinename -suppressinfo $true -hvserver $hvServer`
`}`

**Comment by jackwmc4** [comment]
freythman is correct. You'll want to enumerate the servers. This is by design.
