### ISSUE TITLE
New-HVPool -ReusePreExistingAccounts:$true

### ISSUE THREAD

**Issue by spartyzik** [vmware/PowerCLI-Example-Scripts#180]
New-HVPool -ReusePreExistingAccounts:$true does not work.

I can see where $reusePreExistingAccounts is set from $jsonObject on line 4170, but the spec doesn't appear to be updated from the variable after line 4444.  It is probably my misunderstanding because I don't see anything from customizationSettings, viewStorageAcceleratorSettings, virtualCenterStorageSettings, or virtualCenterNetworkSettings.

-ReusePreExistingAccounts is also missing from the function documentation.

**Comment by spartyzik** [comment]
There is also line 5253 in Get-HV

`$desktopSpecObj.AutomatedDesktopSpec.CustomizationSettings.ReusePreExistingAccounts = $reusePreExistingAccounts`

but $reusePreExistingAccouns hasn't been set at that point.

Would someone please explain how this stuff works?  I am completely lost trying to fix this one.

**Comment by Magneet** [comment]
this issue is still applicable, also when using a spec file it doesn't set the reuse existing accounts

**Comment by freythman** [comment]
Confirmed here as well. I'm looking into this

**Comment by freythman** [comment]
Updated PR #272 with commit https://github.com/freythman/PowerCLI-Example-Scripts/commit/3b5f501d724065c945c0a40d35b379da2d11dabe to address this. 

I tested with Instant Clone and Linked Clone pools via CLI as well as by using a spec file and the `-ReusePreExistingAccounts` parameter was respected each time.

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/272
