### ISSUE TITLE
Remove a machine from a Pool, but not delete it.

### ISSUE THREAD

**Issue by admoseley** [vmware/PowerCLI-Example-Scripts#193]
Is there a function or argument to Remove-HVMachine that removes a VDI from a pool, but does not delete it? Essentially i want to remove it from a pool and add it to another.
In 6.x I would do by manipulating ADAM database, but curious if there's an API command or cmdlet that will allow it this to occur?

thanks in advance.

**Comment by gpeck29** [comment]
Right or Wrong, but I modified the psm1 file. On line #10147 ($deleteSpec.DeleteFromDisk = $true) I changed the $true to $false and tested it. The desktop was removed from Horizon View, but not from vCenter. Maybe a modification of the Remove-HVMachine cmdlet is coming to allow us to use an argument to the function to determine if the machine is removed and deleted or just removed.

**Comment by jrodsguitar** [comment]
I can look into adding an argument as suggested by @gpeck29. 

Maybe I'll have:

Remove from Horizon View but not delete the machine:

Remove-HVMachine -noDelete

**Comment by gpeck29** [comment]
@jrodsguitar The Remove-HVPool already has this parameter, maybe look at it and implement the same way.

**Comment by freythman** [comment]
Added -`DeleteFromDisk` to `Remove-HVMachine` in https://github.com/vmware/PowerCLI-Example-Scripts/pull/222

Defaulted to `$true` so to not remove the machine from vSphere you would set it to false `Remove-HVMachine -MachineName 'VMName01' -DeleteFromDisk:$false`

**Comment by freythman** [comment]
@admoseley #222 was merged. Can you update and try it out?

**Comment by admoseley** [comment]
@freythman Just got around to it and it works like a charm. Thank you sir!

**Comment by admoseley** [comment]
Fixed
