### ISSUE TITLE
"Get-HVEntitlement: No entitlements found with given search parameters" break

### ISSUE THREAD

**Issue by JockserTHD** [vmware/PowerCLI-Example-Scripts#211]
In VMware.HV.Helper.psm1 on line 8122 should be just a return instead of a break.  When calling Get-HVEntitlement that break will stop a script running if not calling Get-HVEntitlement while in a loop.  Had to set up a fake loop for it to break out of so it wouldn't break out of my script.
$once = $true
        while($once){
            $obj.AssignedEntitlements = (Get-HVEntitlement -ResourceName $e.Base.DisplayName -ResourceType GlobalEntitlement).Base.AdDistinguishedName | ?{$_ -match "^CN=GG_VDI\w+"}
            $once = $false
        }

**Comment by Magneet** [comment]
agreed so created a pull request for it

**Comment by Magneet** [comment]
PR as been merged, can you test and if it works close the issue?

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/207
