### ISSUE TITLE
ADD local pools to Global Entitlements 

### ISSUE THREAD

**Issue by benda1606** [vmware/PowerCLI-Example-Scripts#229]
hey,

I made a script that Create Global entitlement in VMware view helper module and assign user\Groups 
but I couldn't  find  a way to add\assign pools to that Global entitlement
is it Possible?
can it be completed by manipulating ADAM database?

**Comment by mtelvers** [comment]
You can use `Set-HVPool -PoolName foo -globalEntitlement bar`
