### ISSUE TITLE
Connect-HVServer missing file(s)

### ISSUE THREAD

**Issue by davidnite** [vmware/PowerCLI-Example-Scripts#267]
Just installed PowerCLI on a brand new HV 7.2 Connection server along with the HV.Helper module.  When running Connect-HVServer, I get the following error:

Connect-HVServer : Could not load file or assembly 'VMware.VimAutomation.Logging.SoapInterceptor, Version=1.0.0.570, Culture=neutral, PublicKeyToken=null' or one of its 
dependencies. The system cannot find the file specified.

I've tried running this from a few remote machines as well, all getting the same error.  Is there some piece of the PowerCLI software I am missing?

**Comment by alsterbrink** [comment]
I Had the same issue as you after removing all older powercli  version.
Solved it by running the below full import, since I do not know what is missing after update of powercli.

Get-Module -Name VMware* -ListAvailable | Import-Module

After running the above It works for me.

Brgrds

Mikael

**Comment by davidnite** [comment]
Thanks for the response, I'm still getting the same error after that.

**Comment by kmruddy** [comment]
You may also want to verify that your antivirus isn't quarantining any of the DLLs that are part of PowerCLI.

**Comment by ibeerens** [comment]
I've got the same error on different systems. All the systems using the latest version of PowerCLI (11.2.0.12483598) with the VMware.VimAutomation.Sdk installed (version 11.2.0.12483635). When importing the SDK mentioned by alsterbrink the "Connect-HVserver" command works without error. It looks like there some issue with the latest PowerCLI (Sdk module) version and the "Connect-HVserver" command.

**Comment by davidnite** [comment]
Same thing I'm seeing, it occurs on all machines I've tried it with.

**Comment by mtelvers** [comment]
Same for me.  I've being trying all day.  Missing VMware.VimAutomation.Logging.SoapInterceptor.  I figured it was because I upgraded from PowerCli 6.5.0 as a bunch of folk seem to have problems with Connect-VI after the upgrade, but it's the same on a clean install.  Connect-VI works but Connect-HV doesn't.  I posted on the PowerShell Gallery in case it got picked up there:
https://www.powershellgallery.com/packages/VMware.VimAutomation.HorizonView/7.6.0.10230451

**Comment by davidnite** [comment]
I finally got it working using version 1.0.0.5334677 of VMware.VimAutomation.Sdk like alsterbrink suggested.  I had to everything related to PowerCLI and reinstall the modules, but it does work now.

**Comment by mtelvers** [comment]
Hi, I too have got it working using the two lines presented by Mikael.  It doesn't work straight away, you just seem to need to do it a bunch of times and close PowerShell in between and reopen it.  Eventually it gets there!

**Comment by kmruddy** [comment]
I've opened a VMware issue on it. Hopefully it can be resolved easily.

**Comment by mtelvers** [comment]
Thanks Kyle.  I also have a problem using `Open-VMConsoleWindow` and need to use the workaround described by LucD [here](https://communities.vmware.com/thread/599395).  This caused me to need to open and close PowerShell a number of times and I found that sometimes `Connect-HVServer` worked and other times it didn't.  The key was to run `Get-Module -Name VMware* -ListAvailable | Import-Module` first in the session.  Running it after `Connect-HVServer` has failed doesn't make it start working.

**Comment by kmruddy** [comment]
All, please update your PowerCLI versions. This issue has been corrected.

**Comment by ibeerens** [comment]
Thanks for the update. The issue is fixed!
