### ISSUE TITLE
Create security server pairing password

### ISSUE THREAD

**Issue by davidnite** [vmware/PowerCLI-Example-Scripts#268]
Would it be possible to add functionality for creating Security Server pairing passwords through this module?

**Comment by davidnite** [comment]
I resolved this on my own.  Feel free to use the below however you like:

`$ViewAPI = $global:DefaultHVServers.ExtensionData
$ConnectionServerId = $ViewAPI.ConnectionServer.ConnectionServer_List()[0].Id
$Secret = ‘suchpassword’
$Bytes = [System.Text.Encoding]::UTF8.GetBytes($Secret)
$SecureString = New-Object VMware.Hv.SecureString
$SecureString.Utf8String = $Bytes
$PairingData = New-Object VMware.Hv.ConnectionServerSecurityServerPairingData
$PairingData.PairingPassword = $SecureString
$PairingData.TimeoutMinutes = 30
$UpdateData = New-Object VMware.Hv.MapEntry
$UpdateData.key = 'securityServerPairing'
$UpdateData.Value = $PairingData
$ViewAPI.ConnectionServer.ConnectionServer_Update($ConnectionServerId,$update)`

**Comment by chatterjeedebojit10** [comment]
hi @davidnite .. does this code code is the fixed password 'suchpassword' for pairing ?
