### ISSUE TITLE
New-HvPool is missing the -Quality switch

### ISSUE THREAD

**Issue by amikkelsendk** [vmware/PowerCLI-Example-Scripts#269]
New-HvPool -InstantClone doesn't allow to set the -Qualify paramater, as it is with -LinkedClone

**Comment by freythman** [comment]
Confirmed. Currently the `$Quality` parameter is only present in the `LINKED_CLONE` parameter set. I'm working on a PR to address this.

**Comment by freythman** [comment]
Created PR https://github.com/vmware/PowerCLI-Example-Scripts/pull/270 to address this

**Comment by amikkelsendk** [comment]
Thanks, much appriciated

**Comment by amikkelsendk** [comment]
Hi,
When wil you merge?

**Comment by amikkelsendk** [comment]
BTW
I tested you changes in #270 and the work perfectly
Thanks for you help
