### ISSUE TITLE
New-HvPool & NewHvFarm: StopOnProvisioningError vs. StopProvisioningOnError

### ISSUE THREAD

**Issue by amikkelsendk** [vmware/PowerCLI-Example-Scripts#273]
In the functions New-HvPool & New-HvFarm, there is a mismatch between the naming standard of StopOnProvisioningError vs. StopProvisioningOnError.

"StopOnProvisioningError" is used in the parameters
but
"StopProvisioningOnError" is used in the process block

This results in the parameter StopOnProvisioningError is never set 

Regards
A.Mikkelsen

**Comment by amikkelsendk** [comment]
I tested locally replacing all "StopOnProvisioningError"  with "StopProvisioningOnError"
And that works, the "Stop Provioning on error" in the GUI is now set correctly

**Comment by freythman** [comment]
I included a fix in Pull https://github.com/vmware/PowerCLI-Example-Scripts/pull/272

**Comment by amikkelsendk** [comment]
thanks
