### ISSUE TITLE
Error when trying to running New-HVPool

### ISSUE THREAD

**Issue by smoonlee** [vmware/PowerCLI-Example-Scripts#286]
When i try and deploy a new HVPool i get the following error 

Exception calling "Desktop_Create" with "2" argument(s): "There is an error in the XML document."
At C:\Program Files\WindowsPowerShell\Modules\VMware.Hv.Helper\VMware.HV.Helper.psm1:4887 char:7
+       $id = $desktop_helper.Desktop_create($services,$desktopSpecObj)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
 

Base                  : VMware.Hv.DesktopBase
DesktopSettings       : VMware.Hv.DesktopSettings
Type                  : AUTOMATED
AutomatedDesktopSpec  : VMware.Hv.DesktopAutomatedDesktopSpec
ManualDesktopSpec     :
RdsDesktopSpec        :
GlobalEntitlementData :

The PowerShell Code I'm using is

New-HVPool -HvServer $L_Horizon -LinkedClone -PoolName $L_VDIPoolName -PoolDisplayName $L_VDIDisplayName -Enable $true `
-UserAssignment FLOATING -ParentVM $L_VDITemplate -SnapshotVM $L_BaseSnapshot -Datastores $L_VDIDatastore -VmFolder 'VDI' `
-HostOrCluster $L_VDIClusterName -ResourcePool $L_VDIResourcePool -NamingMethod PATTERN -NamingPattern 'LW10FN-108D-{n:fixed=2}' `
-CustType 'QUICK_PREP' -MinReady '3' -MaximumCount '5' -SpareCount '3' -ViewComposerDiskTypes '0' -AdContainer 'OU=xx,OU=xx,OU=xx,OU=xx' 

It worked fine last week and i haven't changed anything on the Server went to try run a test build this morning and got the above error. - Tested on my Workstation PC and also get the same error.

**Comment by freythman** [comment]
Can you run the same command with the `-WhatIf` parameter? This will trigger a test on your inputs.

On a precursory look, everything looks ok input wise, but I haven't had time to test it yet.

**Comment by smoonlee** [comment]
Using the -WhatIf Parameter it returns: What if: Performing the operation "New-HVPool" on target "108-LW10-002D".

Base                  : VMware.Hv.DesktopBase
DesktopSettings       : VMware.Hv.DesktopSettings
Type                  : AUTOMATED
AutomatedDesktopSpec  : VMware.Hv.DesktopAutomatedDesktopSpec
ManualDesktopSpec     : 
RdsDesktopSpec        : 
GlobalEntitlementData :
