### ISSUE TITLE
Is there any way to set VM to maintenance mode using View PowerCLI?

### ISSUE THREAD

**Issue by tcpip98** [vmware/PowerCLI-Example-Scripts#297]
Hey guys,

Is there any way to set specific dedicated VM to maintenance mode using View PowerCLI?
And also disable the maintenance mode, vice versa.

**Comment by freythman** [comment]
@tcpip98, certainly. Try: `Set-HVMachine -MachineName "NameOfVM" -Maintenance`

**Comment by tcpip98** [comment]
@freythman, Thank you so~~ much! It works well~!
