### ISSUE TITLE
New-HVPreInstalledApplication does not have ID parameter

### ISSUE THREAD

**Issue by chipzoller** [vmware/PowerCLI-Example-Scripts#303]
This cmdlet does not have an ID parameter which allows a user to define the ID for a pre-installed application and, by default, the `ApplicationName` parameter is also used for the ID. This is a problem because if this cmdlet was used previously to create an application like "Calculator", then it cannot be used subsequently on another farm to create the same "Calculator" application. Attempts to do so throws the message "<app_name> already exists in the Application Pool." And since the `ApplicationName` parameter must match the name of the pre-installed application, you're just stuck if you need to publish the same application name from different farms.

Is there a workaround here?

**Comment by freythman** [comment]
@chipzoller Good point. I'll add an ID parameter to allow for multiple applications of the same type.

**Comment by chipzoller** [comment]
That would be so awesome, @freythman! Not to be pushy because your response is super appreciated, but is that something that could be added relatively soon? Currently working on an automation project and, like, really need this as it's the last hurdle 😃 **Much** thanks!

**Comment by freythman** [comment]
Updated in PR #302 
Awaiting merge, but if you're in a rush you can download directly from my fork: https://github.com/freythman/PowerCLI-Example-Scripts/tree/master/Modules/VMware.Hv.Helper

**Comment by chipzoller** [comment]
Awesome, @freythman. When that gets merged into the master branch, I'll pull it down and test that parameter and then report back. Much appreciated for the super fast turnaround!

**Comment by freythman** [comment]
Looks like we're merged if you want to give it a go, now.

**Comment by chipzoller** [comment]
Confirmed. Tested multiple builds with the new param and it works just perfectly. You deserve a beer, sir, for your work. Multiple and many thanks.

**Comment by freythman** [comment]
Glad to hear!

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/302
