### ISSUE TITLE
Connect-VMCVIServer and Connect-NSXTProxy Return Error

### ISSUE THREAD

**Issue by seanpmassey** [vmware/PowerCLI-Example-Scripts#312]
Attempting to use Connect-VMCVIServer function returns the following error:
*Unable to cast object of type 'vmware.vapi.data.OptionalValue' to type 'vmware.vapi.data.StringValue'.*

Digging through the modules, it looks like this section of code (starting at line 136 of VMware.VMC.psm1) is failing:
*$sddcService = Get-VMCService com.vmware.vmc.orgs.sddcs
$sddcService.list($OrgID) | Where {$_.name -match $Name}*

This might be an issue with the VMware.VIMAutomation.VMC module since the Get-VMCService command comes from that module.  

I am also seeing this issue with the Connect-NSXTProxy function.

I have encountered this issue on Windows 10 and MacOS using PowerShell Core 6.2.3 and the latest PowerCLI and VMC modules.  I have tested against multiple SDDCs including provisioning a new one, and I'm seeing the issue on all of them.

**Comment by kmruddy** [comment]
I've validated that I believe this to be an issue with PowerCLI and the VMC module itself. I have created an internal request to correct the module.

**Comment by kmruddy** [comment]
This issue has been corrected and is now functional.
