### ISSUE TITLE
VMware.Hv.Helper Set-HVPool to Remove Pool from Global Entitlement

### ISSUE THREAD

**Issue by bfett20** [vmware/PowerCLI-Example-Scripts#342]
We've been able to automate adding pools to global entitlements using Set-HVPool but have not been able to replicate this functionality for removal by setting the value of -globalEntitlement to $null (also tried "" and '' to be thorough).  This would be useful in our Active/Active environment when we need to take down a pod for maintenance or upgrades.

**Comment by mtelvers** [comment]
For your use case wouldn't you just do `Set-HVPool -disable`

**Comment by mtelvers** [comment]
I have created PR #343 which adds a new switch -clearGlobalEntitlement to Set-HVPool

**Comment by bfett20** [comment]
Fantastic, thank you!!  Disabling the pool is effective for select scenarios, but in some cases we need to manipulate the pools in some way during the maintenance window that wouldn't get processed fully if the pools were disabled.
