### ISSUE TITLE
Get-HVEvent timeout issue

### ISSUE THREAD

**Issue by D-Alberto** [vmware/PowerCLI-Example-Scripts#364]
Get-HVEvent -HvDbServer $eventdb -TimePeriod day  -Verbose
Output is:
Exception calling "Fill" with "1" argument(s): "Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."

How can i mitigate this issue? 
Playing the command again after a few tries works.

Thx Alberto

**Comment by TwoFaceSteph** [comment]
I have the exact same issue, it would be nice to have a paramter -timeout to specify how long the database request should take (in seconds). Actually this leads to gaining results sometimes but not always which is a bit annoying.
Thx in advance 
Stephan

**Comment by D-Alberto** [comment]
I have found a workaround:
i had included in my script **VMware.HV.Helper.psm1**

you can find on https://github.com/vmware/PowerCLI-Example-Scripts/blob/master/Modules/VMware.Hv.Helper/VMware.HV.Helper.psm1

I wrote something like this in my script
**Import-Module "D:\Modules\VMware.HV.Helper.psm1" -Force**

In module i have added one command at line 1004
1003    $DataTable = New-Object System.Data.DataTable
**1004    $adapter.SelectCommand.CommandTimeout=300**
1005    $adapter.Fill($DataTable)

I think this happens because the DB times out in the execution of the query. Next step for me it's to use a dedicated DB server.

Try it and let me know.

Alberto
