### ISSUE TITLE
Set-HVPool - Try to modify pool template - Error

### ISSUE THREAD

**Issue by Sgwalker1969** [vmware/PowerCLI-Example-Scripts#371]
Hi, how explain on subject, I would like to modify pool template by using the cmdlet Set-HVPool; I try the following code:

Set-HVPoll -PoolNmae "poolName' -key "AutomatedDesktopData.VirtualCenterProvisioningSettings.VirtualCenterProvisioningData.Template" -value 'NewTemplate'

I receive this error:

Exception calling "Desktop_Update" with "3" argument(s):

Error Message : "Invalid member name.

Could you help me?

Thanks

**Comment by psurad** [comment]
Hi,
Please change the key to match the case of properties in the API docs as below:
 'automatedDesktopData.virtualCenterProvisioningSettings.virtualCenterProvisioningData.template' 

Refer link for API docs: https://code.vmware.com/apis/956/view

Thanks.

**Comment by Sgwalker1969** [comment]
Thank you so much! It's works.

Have a nice day

> Hi,
> Please change the key to match the case of properties in the API docs as below:
> 'automatedDesktopData.virtualCenterProvisioningSettings.virtualCenterProvisioningData.template'
> 
> Refer link for API docs: https://code.vmware.com/apis/956/view
> 
> Thanks.

Thank you so much! It's works.

Have a nice day
