### ISSUE TITLE
New-WorkloadManagement fails with Address . is not a valid IP address or FQDN.

### ISSUE THREAD

**Issue by sudhakarau1** [vmware/PowerCLI-Example-Scripts#375]
Following the steps in https://www.virtuallyghetto.com/2020/05/workload-management-powercli-module-for-automating-vsphere-with-kubernetes.html
`Connect-CisServer -Server vcsa-wcp.xyz.com -User user@xyz.com -Password password`

```
PS C:\Users\Administrator> $workloadManagementParameters = @{
>> ClusterName = "k8s-cluster"
>> ControlPlaneSize = "small"
>> MgmtNetwork = "DVPG-Management Network"
>> MgmtNetworkStartIP = "192.168.1.60"
>> MgmtNetworkSubnet = "255.255.255.0"
>> MgmtNetworkGateway = "192.168.1.1"
>> MgmtNetworkDNS = "192.168.1.1"
>> MgmtNetworkDNSDomain = "xyz.com"
>> MgmtNetworkNTP = "10.142.7.1"
>> WorkloadNetworkVDS = "k8s-VDS"
>> WorkloadNetworkEdgeCluster = "Edge-Cluster-01"
>> WorkloadNetworkDNS = "192.168.1.1"
>> WorkloadNetworkIngressCIDR = "192.168.2.0/25"
>> WorkloadNetworkEgressCIDR = "192.168.2.128/25"
>> ControlPlaneStoragePolicy = "k8s-gold-storage-policy"
>> EphemeralDiskStoragePolicy = "k8s-gold-storage-policy"
>> ImageCacheStoragePolicy = "k8s-gold-storage-policy"
>> }
```

`PS C:\Users\Administrator> New-WorkloadManagement @workloadManagementParameters`
```console
Enabling Workload Management on vSphere Cluster k8s-cluster ...
New-WorkloadManagement: Error in attempting to enable Workload Management on vSphere Cluster k8s-cluster
New-WorkloadManagement:
(A server error occurred: 'com.vmware.vapi.std.errors.error': Address . is not a valid IP address or FQDN. (Server error id: 'vcenter.wcp.address.invalid'). Check $Error[0].Exception.ServerError for more details..Exception.Message)
```

**Comment by fgrehl** [comment]
It might be a problem with the NTP server. You can see what's happening in wcpsvc.log on the vCenter server. This is what the WCP is trying to create:

`                        "master_NTP_servers": {
                            "OPTIONAL": [
                                "1",
                                "8",
                                "5",
                                ".",
                                "1",
                                "2",
                                "0",
                                ".",
                                "2",
                                "2",
                                ".",
                                "1",
                                "2"
                            ]
                        },`

**Comment by fgrehl** [comment]
It was the NTP parameter not being cast as string.

Change line 86 to the following and it will work:

`[Parameter(Mandatory=$True)][string[]]$MgmtNetworkNTP,`
