### ISSUE TITLE
Enhance Disconnect-SsoAdminServer to support asterisk 

### ISSUE THREAD

**Issue by lamw** [vmware/PowerCLI-Example-Scripts#387]
Just tried out the new PowerCLI SSO Module and when disconnecting from the server, it doesn't behave like other PowerCLI disconnect-* commands where you can pass in * (asterisk).

In fact, I didn't save the connection, so I had to look up the global variable and even using `$Global:DefaultSsoAdminServers` didn't work as it expected a specific entry. 

Ultimately, I needed to use:
```
Disconnect-SsoAdminServer -Server $Global:DefaultSsoAdminServers[0]
```

Ideally, we can simply do:
```
Disconnect-SsoAdminServer * -Confirm:$false
```

or even have `$Global:DefaultSsoAdminServer` also defined like we do for Connect-VIServer cmdlet

**Comment by qlikq** [comment]
I have raised a PR for this , for similar thing. I have enabled automatic disconnect in case one is connected to a single SSO server. If the * is needed, to handle more i can add it as well. #388

**Comment by dmilov** [comment]
This request is for the so called OBN PowerCLI feature. Will do it for Server parameter.
