### ISSUE TITLE
Get-HVSummary Issues

### ISSUE THREAD

**Issue by dfoley84-zz** [vmware/PowerCLI-Example-Scripts#398]
The Following Get-HVSummary is displaying Issue, which fails to export some machines to CSV.

```
Import-Module VMware.VimAutomation.HorizonView
Import-Module VMware.VimAutomation.Core
Get-Module -ListAvailable 'VMware.Hv.Helper' | Import-Module



connect-hvserver 
Connect-VIServer 


$vms = Get-HVMachineSummary

$results = @()

foreach($vm in $vms){

     $machine = $null

     $machine = Get-VM -Name $vm.Base.Name
     

     $properties = @{

     MachineName = $vm.Base.Name
     VDIPool = $vm.NamesData.DesktopName
  


     }

     $results += New-Object psobject -Property $properties

}

$results | export-csv -NoTypeInformation -path C:\Test.
```

```
Exception calling "QueryService_GetNext" with "2" argument(s): "ExceptionType 
: VMware.Hv.EntityNotFound
ErrorMessage : Could not find user or group in AD
Id : VMware.Hv.UserOrGroupId"
At C:\Program 
Files\WindowsPowerShell\Modules\VMware.Hv.Helper\VMware.HV.Helper.psm1:7446 
char:23
+ ... $GetNext) { $queryResults = $query_service_helper.QueryService_GetNex ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : VimException
```

**Comment by bwuch** [comment]
Hello @dfoley84-zz, I was looking through some open issues in this repo and came across this thread.  I believe the error you were seeing is similar to this KB article: https://kb.vmware.com/s/article/2148374 and may be resolved in newer versions of PowerCLI.  The latest version of the HorizonView module is 12.3, you can confirm the version you have now with `Get-Module VMware.VimAutomation.HorizonView | Select-Object Version`.

Additionally, I noticed that you are connecting to both Horizon and vCenter Server in this code, and finding the VM in the vCenter Server inventory and storing that as $machine, but $machine is not used later in the script.  Assuming you didn't redact some of the  example code, I believe you could achieve the same results with something like this, only connected to Horizon:

`Get-HVMachineSummary | Select-Object @{Name='MachineName';Expression={$_.Base.Name}}, @{Name='VDIPool';Expression={$_.NamesData.DesktopName}} | Export-Csv -NoTypeInformation -Path C:\Test.csv`

Hope this helps!
