### ISSUE TITLE
New-HVFarm fails when $maxSessionsType is set to "LIMITED" as it is incorrectly being set in line 2786

### ISSUE THREAD

**Issue by kchoudhury** [vmware/PowerCLI-Example-Scripts#400]
For vmware.hv.helper module , the function New-HVFarm is incorrectly setting the $maxSessionsType for the $farmspecobject due to which if you pass the $maxSessionsType parameter value to LIMITED the api request sent is incorrect and sets the $maxsession value instead of $maxSessionsType:

Problem lies in line number 2786 -
```
$farmSpecObj.AutomatedFarmSpec.RdsServerMaxSessionsData.MaxSessionsType = $maxSessionsType
        if ($maxSessionsType -eq "LIMITED") {
            $farmSpecObj.AutomatedFarmSpec.RdsServerMaxSessionsData.MaxSessionsType = $maxSessions
        }
```

**Correct code should be to set MaxSessions in this condition as given below:**

```
$farmSpecObj.AutomatedFarmSpec.RdsServerMaxSessionsData.MaxSessionsType = $maxSessionsType
        if ($maxSessionsType -eq "LIMITED") {
            $farmSpecObj.AutomatedFarmSpec.RdsServerMaxSessionsData.MaxSessions = $maxSessions
        }
```

**Comment by bitszor** [comment]
Can confirm the fix in the original issue will allow farms to be provisioned with max sessions set to limited after above pull request is merged.

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/412
