### ISSUE TITLE
Get-hvpool information about maximum number of desktops in pool

### ISSUE THREAD

**Issue by D-Alberto** [vmware/PowerCLI-Example-Scripts#408]
I cannot find way to retrive the  maximum number of desktop configured in a desktop pool.
Thx

**Comment by freythman** [comment]
AFAIK, this isn't stored in the API, but rather comes from documented guidance and depends on the pool type, Horizon version, etc...

For Horizon 7 - https://kb.vmware.com/s/article/2150348
For Horizon 8 - https://configmax.vmware.com/guest?vmwareproduct=Horizon&release=Horizon%202012&categories=46-0

**Comment by Magneet** [comment]
I think @D-Alberto means the maximum amount of machines that already has been configured on the pool. This is stored under AutomatedDesktopData.VmNamingSettings.PatternNamingSettings 
![image](https://user-images.githubusercontent.com/27762574/110285569-b66f8e00-7fe3-11eb-808c-ebfbe1db33ee.png)

**Comment by freythman** [comment]
On second pass, I believe you're right. I should have had a second coffee before replying

**Comment by D-Alberto** [comment]
Thank you so much that's exactly what I was looking for.
