### ISSUE TITLE
Connect-SsoAdminServer - the connection fails with the below error. 

### ISSUE THREAD

**Issue by wagsbjj** [vmware/PowerCLI-Example-Scripts#413]
New-Object : Exception calling ".ctor" with "4" argument(s): "One or more errors occurred."
At C:\Users\us44800\OneDrive - Premera Blue Cross\Documents\WindowsPowerShell\Modules\VMware.vSphere.SsoAdmin\VMware.vSphere.SsoAdmin.psm1:131 char:25
+       $ssoAdminServer = New-Object `
+                         ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by dmilov** [comment]
Fixed error handling. You should be able to see what's the server error with the latest.
Let me know how the error looks like. I believe it is somehow related to credentials.
