### ISSUE TITLE
New-HvPool does not set ReusePreExistingAccounts properly for Full Clone Automated requests

### ISSUE THREAD

**Issue by TheRealBenForce** [vmware/PowerCLI-Example-Scripts#436]
Horizon 7.13
Steps to reproduce
Make a new pool using parameters:

New-HvPool -FullClone `
-PoolName $PoolName `
-PoolDisplayName $PoolDisplayName `
...
-ReusePreExistingAccounts $true

Then load horizon and look at pool customization. You will see the box "Allow Reuse of Existing Computer Accounts" is not checked.

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/438
