### ISSUE TITLE
New-HvPool - Many configuration parameters are unavailable to Full Clone pools

### ISSUE THREAD

**Issue by TheRealBenForce** [vmware/PowerCLI-Example-Scripts#437]
The New-HvPool cmdlet uses ParameterSetName to determine what configuration parameters are available to the various clone/pool types. Many parameters that should be available to FullClones are locked away because there is no ParameterSetName for FULL_CLONE. 

For example:
#desktopSpec.desktopSettings.logoffSettings.allowUsersToChooseProtocol
[Parameter(Mandatory = $false,ParameterSetName = 'INSTANT_CLONE')]
[Parameter(Mandatory = $false,ParameterSetName = "LINKED_CLONE")]
[Parameter(Mandatory = $false,ParameterSetName = 'MANUAL')]
[int]$allowUsersToChooseProtocol = $true,

**Comment by kamennikolov** [comment]
Fixed with https://github.com/vmware/PowerCLI-Example-Scripts/pull/438
