### ISSUE TITLE
Pulling disabled/locked information for vCenter users

### ISSUE THREAD

**Issue by quattad** [vmware/PowerCLI-Example-Scripts#439]
Hi,

I would like to get information for local vCenter users including whether the users are 1) disabled 2) locked.

 Currently, I am using the Get-SsoPersonUser module from [VMware.vSphere.SsoAdmin](https://github.com/vmware/PowerCLI-Example-Scripts/tree/master/Modules/VMware.vSphere.SsoAdmin).

However, the fields returned are only Name, Domain, Description, FirstName, LastName and EmailAddress.
Would it be possible to modify this module to also fetch whether users are disabled and/or locked? Or are there already existing modules that can get such information.

Thanks.

**Comment by dmilov** [comment]
Added `Locked` and `Disabled` properties to the Get-SsoPersonUser result.

Fixed in version 1.2.3 available on GitHub and PSGallery

**Comment by quattad** [comment]
> Added `Locked` and `Disabled` properties to the Get-SsoPersonUser result.
> 
> Fixed in version 1.2.3 available on GitHub and PSGallery

Thanks @dmilov !
