### ISSUE TITLE
Import the module at macOS? What folder?

### ISSUE THREAD

**Issue by rstolpe** [vmware/PowerCLI-Example-Scripts#442]
Hi,
I have installed PS and PowerCli and well it work great but where should I put the Hv.Helper module?
What folder?

I'm a little confused regarding that.

**Comment by wss-978** [comment]
Use $env:PSModulepath to know the module paths
Use Get-Modules -listavailable to list the modules.

Where all the VMware.* Modules appear copy the VMware.hv.helper module
there.
Thanks,
Waseem
