### ISSUE TITLE
Instant clone pool with .json file ErrorMessage : A null value is invalid.       viewComposerDiskTypes"

### ISSUE THREAD

**Issue by wesllleyyy** [vmware/PowerCLI-Example-Scripts#447]
Hello I am having a hard time creating a instant clone pool with a json file. (a linked-clone pool doesnt have any isseu)

Exception calling "Desktop_Create" with "2" argument(s): "ExceptionType : VMware.Hv.InvalidArgument
ErrorMessage : A null value is invalid.
ParameterName : automatedDesktopSpec.virtualCenterProvisioningSettings.virtualCenterStorageSettings.viewStorageAcceleratorSettings.viewComposerDiskTypes"
At C:\Program Files\WindowsPowerShell\Modules\VMware.Hv.Helper\VMware.HV.Helper.psm1:4983 char:7
+       $id = $desktop_helper.Desktop_create($services,$desktopSpecObj)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : VimException

When i look in the json file its filled with :
"ViewComposerDiskTypes":  "OS_DISKS",

Is there anything i can do about it

my json file

{
    "Base":  {
                 "accessGroup":  "Root",
                 "description":  null,
                 "name":  "test1",
                 "displayName":  "test1"
             },
    "DesktopSettings":  {
                            "Enabled":  true,
                            "Deleting":  false,
                            "ConnectionServerRestrictions":  null,
                            "LogoffSettings":  {
                                                   "PowerPolicy":  "ALWAYS_POWERED_ON",
                                                   "AutomaticLogoffPolicy":  "AFTER",
                                                   "AutomaticLogoffMinutes":  120,
                                                   "AllowUsersToResetMachines":  false,
                                                   "AllowMultipleSessionsPerUser":  false,
                                                   "DeleteOrRefreshMachineAfterLogoff":  "DELETE",
                                                   "RefreshOsDiskAfterLogoff":  "NEVER",
                                                   "RefreshPeriodDaysForReplicaOsDisk":  null,
                                                   "RefreshThresholdPercentageForReplicaOsDisk":  null,
                                                   "EmptySessionTimeoutPolicy":  null,
                                                   "EmptySessionTimeoutMinutes":  null,
                                                   "LogoffAfterTimeout":  null,
                                                   "PreLaunchSessionTimeoutPolicy":  null,
                                                   "PreLaunchSessionTimeoutMinutes":  null
                                               },
                            "DisplayProtocolSettings":  {
                                                            "SupportedDisplayProtocols":  [
                                                                                              "BLAST",
                                                                                              "PCOIP",
                                                                                              "RDP"
                                                                                          ],
                                                            "DefaultDisplayProtocol":  "BLAST",
                                                            "AllowUsersToChooseProtocol":  true,
                                                            "PcoipDisplaySettings":  {
                                                                                         "Renderer3D":  "MANAGE_BY_VSPHERE_CLIENT",
                                                                                         "EnableGRIDvGPUs":  true,
                                                                                         "VGPUGridProfile":  "grid_m10-1b",
                                                                                         "VRamSizeMB":  null,
                                                                                         "VRamSizeKB":  null,
                                                                                         "MaxNumberOfMonitors":  null,
                                                                                         "MaxResolutionOfAnyOneMonitor":  null
                                                                                     },
                                                            "EnableHTMLAccess":  true,
                                                            "EnableCollaboration":  false
                                                        },
                            "FlashSettings":  {
                                                  "Quality":  "NO_CONTROL",
                                                  "Throttling":  "DISABLED"
                                              },
                            "MirageConfigurationOverrides":  {
                                                                 "OverrideGlobalSetting":  false,
                                                                 "Enabled":  null,
                                                                 "Url":  null
                                                             },
                            "CategoryFolderName":  null,
                            "ClientRestrictions":  false,
                            "ShortcutLocations":  null,
                            "AllowMultipleSessionsPerUser":  false,
                            "SupportedSessionType":  "DESKTOP",
                            "CloudManaged":  false,
                            "CloudAssigned":  false,
                            "DisplayAssignedMachineName":  false,
                            "DisplayMachineAlias":  false
                        },
    "Type":  "AUTOMATED",
    "AutomatedDesktopSpec":  {
                                 "virtualCenterProvisioningSettings":  {
                                                                           "EnableProvisioning":  true,
                                                                           "StopProvisioningOnError":  true,
                                                                           "MinReadyVMsOnVComposerMaintenance":  0,
                                                                           "VirtualCenterProvisioningData":  {
                                                                                                                 "datacenter":  "/VxRail",
                                                                                                                 "parentVm":  "W10_1909.2_Test",
                                                                                                                 "hostOrCluster":  "/VxRail/host/VxRail-Virtual-SAN-MER1",
                                                                                                                 "resourcePool":  "/VxRailhost/VxRail-Virtual-SAN-MER1/Resources",
                                                                                                                 "snapshot":  "Instant-Clone-2",
                                                                                                                 "vmFolder":  "/VxRail-MER1/vm",
                                                                                                                 "template":  null
                                                                                                             },
                                                                           "VirtualCenterStorageSettings":  {
                                                                                                                "Datastores":  {
                                                                                                                                   "storageOvercommit":  "UNBOUNDED",
                                                                                                                                   "datastore":  "/VxRail/host/VxRail-Virtual-SAN-MER1/VxRail-Virtual-SAN-Datastore"
                                                                                                                               },
                                                                                                                "UseVSan":  true,
                                                                                                                "ViewComposerStorageSettings":  {
                                                                                                                                                    "UseSeparateDatastoresReplicaAndOSDisks":  false,
                                                                                                                                                    "ReplicaDiskDatastore":  null,
                                                                                                                                                    "UseNativeSnapshots":  false,
                                                                                                                                                    "SpaceReclamationSettings":  {
                                                                                                                                                                                     "ReclaimVmDiskSpace":  false,
                                                                                                                                                                                     "ReclamationThresholdGB":  null
                                                                                                                                                                                 },
                                                                                                                                                    "PersistentDiskSettings":  {
                                                                                                                                                                                   "RedirectWindowsProfile":  false,
                                                                                                                                                                                   "UseSeparateDatastoresPersistentAndOSDisks":  false,
                                                                                                                                                                                   "PersistentDiskDatastores":  null,
                                                                                                                                                                                   "DiskSizeMB":  null,
                                                                                                                                                                                   "DiskDriveLetter":  null
                                                                                                                                                                               },
                                                                                                                                                    "NonPersistentDiskSettings":  {
                                                                                                                                                                                      "RedirectDisposableFiles":  false,
                                                                                                                                                                                      "DiskSizeMB":  null,
                                                                                                                                                                                      "DiskDriveLetter":  null
                                                                                                                                                                                  }
                                                                                                                                                },
                                                                                                                "ViewStorageAcceleratorSettings":  {
                                                                                                                                                       "UseViewStorageAccelerator":  true,
                                                                                                                                                       "ViewComposerDiskTypes":  "OS_DISKS",
                                                                                                                                                       "RegenerateViewStorageAcceleratorDays":  7,
                                                                                                                                                       "BlackoutTimes":  null
                                                                                                                                                   }
                                                                                                            },
                                                                           "VirtualCenterNetworkingSettings":  {
                                                                                                                   "Nics":  [
                                                                                                                                {
                                                                                                                                    "Nic":  {
                                                                                                                                                "Id":  "NetworkInterfaceCard/OWE4OTNjMDYtOWUxYi00NzAzLWEyYTUtM2M1YjBjY2M3Yjgw/NzYwYjRhODYtZTlkNC00YWRjLWFhOTAtYWY0Njg0ZDE4MDEx/TmV0d29yayBhZGFwdGVyIDE"
                                                                                                                                            },
                                                                                                                                    "NetworkLabelAssignmentSpecs":  [
                                                                                                                                                                        {
                                                                                                                                                                            "Enabled":  true,
                                                                                                                                                                            "NetworkLabel":  {
                                                                                                                                                                                                 "Id":  "NetworkLabel/OWE4OTNjMDYtOWUxYi00NzAzLWEyYTUtM2M1YjBjY2M3Yjgw/NzYwYjRhODYtZTlkNC00YWRjLWFhOTAtYWY0Njg0ZDE4MDEx/ZHYtMDQtUElUVklFVw"
                                                                                                                                                                                             },
                                                                                                                                                                            "MaxLabelType":  "UNLIMITED",
                                                                                                                                                                            "MaxLabel":  null
                                                                                                                                                                        }
                                                                                                                                                                    ]
                                                                                                                                }
                                                                                                                            ]
                                                                                                               },
                                                                           "AddVirtualTPM":  false
                                                                       },
                                 "userAssignment":  {
                                                        "UserAssignment":  "FLOATING",
                                                        "AutomaticAssignment":  true,
                                                        "AllowMultipleAssignments":  false
                                                    },
                                 "customizationSettings":  {
                                                               "CustomizationType":  "CLONE_PREP",
                                                               "DomainAdministrator":  null,
                                                               "AdContainer":  "OU=Test,OU=Virtueel,OU=Clients,OU=Parkstad-IT,OU=Organisaties",
                                                               "ReusePreExistingAccounts":  false,
                                                               "NoCustomizationSettings":  null,
                                                               "SysprepCustomizationSettings":  null,
                                                               "QuickprepCustomizationSettings":  null,
                                                               "CloneprepCustomizationSettings":  {
                                                                                                      "InstantCloneEngineDomainAdministrator":  "vdisysprep",
                                                                                                      "PowerOffScriptName":  null,
                                                                                                      "PowerOffScriptParameters":  null,
                                                                                                      "PostSynchronizationScriptName":  null,
                                                                                                      "PostSynchronizationScriptParameters":  null,
                                                                                                      "PrimingComputerAccount":  null
                                                                                                  }
                                                           },
                                 "virtualCenter":  "172.30.21.189",
                                 "vmNamingSpec":  {
                                                      "namingMethod":  "PATTERN",
                                                      "patternNamingSettings":  {
                                                                                    "NamingPattern":  "testwes{n:fixed=3}",
                                                                                    "MaxNumberOfMachines":  15,
                                                                                    "NumberOfSpareMachines":  1,
                                                                                    "ProvisioningTime":  "ON_DEMAND",
                                                                                    "MinNumberOfMachines":  6
                                                                                },
                                                      "specificNamingSpec":  null
                                                  },
                                 "provisioningType":  "INSTANT_CLONE_ENGINE",
                                 "virtualCenterManagedCommonSettings":  {
                                                                            "TransparentPageSharingScope":  "VM"
                                                                        }
                             },
    "ManualDesktopSpec":  null,
    "RdsDesktopSpec":  null,
    "GlobalEntitlementData":  null
}

**Comment by chriskoch99** [comment]
What was the resolution here?  Having the same problem.

**Comment by logicbo0mb** [comment]
> What was the resolution here? Having the same problem.

Hi, could you manage to solve the problem so far?
