### ISSUE TITLE
[VMware.vSphere.SsoAdmin] - Include password expiry information when using Get-SsoPersonUser

### ISSUE THREAD

**Issue by lamw** [vmware/PowerCLI-Example-Scripts#460]
When using dir-cli command within the VCSA, password expiry information for a specific user can be included. It looks like the Get-SsoPersonUser does not include this information and would be extremely useful. Please see https://williamlam.com/2021/06/quick-tip-how-to-check-password-expiry-for-a-specific-vsphere-sso-user.html for more details

**Comment by dmilov** [comment]
Fixed in version 1.3.1 available on PSGallery.
