### ISSUE TITLE
Feature request: Add ability to enable/disable SsoPersonUser in VMware.vSphere.SsoAdmin module

### ISSUE THREAD

**Issue by mikedonleyuoy** [vmware/PowerCLI-Example-Scripts#470]
Currently the module supports creating/deleting SSOpersonuser accounts, however, in a normal lifecycle, it is desirable to disable an account prior to it's removal.

With the current module, this is currently not possible so to temporarily disable a user account would mean changing the users password to something random and/or removing them from a SSO group.

I'd like to request the addition of a -Enable:$true/$false switch to Set-SsoPersonUser cmdlet, or new cmdlets of Enable-SsoPersonUser and Disable-SsoPersonUser.

**Comment by dmilov** [comment]
Thanks for this request. I'll implement it soon

**Comment by dmilov** [comment]
Implemented.
New version of the module `1.3.2` is available with the feature.

https://www.powershellgallery.com/packages/VMware.vSphere.SsoAdmin/1.3.2
