### ISSUE TITLE
Sample to encrypt VM using Native Key Provider

### ISSUE THREAD

**Issue by reubenur-rahman** [vmware/PowerCLI-Example-Scripts#480]
Please provide a sample to encrypt VM using the native key provider.

**Comment by kamennikolov** [comment]
How about example#7 of Set-VM here: https://developer.vmware.com/docs/powercli/latest/vmware.vimautomation.core/commands/set-vm/#EncryptParameterSet. Is that what you're looking for?

**Comment by reubenur-rahman** [comment]
Thanks! It works.
