### ISSUE TITLE
No command recognized

### ISSUE THREAD

**Issue by imtrinity94** [vmware/PowerCLI-Example-Scripts#500]
Get-HVPool : The term 'Get-HVPool' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-HVPool -PoolName 'vmwarepool' | New-HVPool -PoolName 'clonedPool' ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-HVPool:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by freythman** [comment]
@imtrinity94 can you provide some more information? What version of PowerShell are you using? What version of PowerCLI? Can you run `Get-Module` and provide the output?

**Comment by imtrinity94** [comment]
PS C:\Windows\system32> Get-Module vmware.vimautomation.ho* | Format-List


Name              : VMware.VimAutomation.HorizonView
Path              : C:\Program Files\WindowsPowerShell\Modules\VMware.VimAutomation.HorizonView\12.3.0.18592768\VMware.VimAutomation.HorizonView.psm1
Description       : This Windows PowerShell module contains Connect/Disconnect cmdlets for View API service.
ModuleType        : Script
Version           : 12.3.0.18592768
NestedModules     : {VMware.VimAutomation.HorizonView}
ExportedFunctions :
ExportedCmdlets   : {Connect-HVServer, Disconnect-HVServer}
ExportedVariables :
ExportedAliases   :

**Comment by imtrinity94** [comment]
Powershell version is 5.1.14393 and PowerClI version is 12.3.0.17860403.

**Comment by imtrinity94** [comment]
Also, Connect-HvServer is working perfect.

**Comment by imtrinity94** [comment]
PS C:\Windows\system32> $hvserver.ExtensionData


ADContainer                           : VMware.Hv.ADContainer
ADDomain                              : VMware.Hv.ADDomain
ADDomainHealth                        : VMware.Hv.ADDomainHealth
ADUserOrGroup                         : VMware.Hv.ADUserOrGroup
AccessGroup                           : VMware.Hv.AccessGroup
AdminUserOrGroup                      : VMware.Hv.AdminUserOrGroup
AdvancedSettings                      : VMware.Hv.AdvancedSettings
Application                           : VMware.Hv.Application
ApplicationIcon                       : VMware.Hv.ApplicationIcon
AuditEvent                            : VMware.Hv.AuditEvent
AuthenticationManager                 : VMware.Hv.AuthenticationManager
BaseImageSnapshot                     : VMware.Hv.BaseImageSnapshot
BaseImageVm                           : VMware.Hv.BaseImageVm
CEIP                                  : VMware.Hv.CEIP
CategoryFolder                        : VMware.Hv.CategoryFolder
Certificate                           : VMware.Hv.Certificate
CertificateSSOConnector               : VMware.Hv.CertificateSSOConnector
CertificateSSOConnectorHealth         : VMware.Hv.CertificateSSOConnectorHealth
CertificateSSOEnrollmentServer        : VMware.Hv.CertificateSSOEnrollmentServer
Cluster                               : VMware.Hv.Cluster
ConnectionServer                      : VMware.Hv.ConnectionServer
ConnectionServerHealth                : VMware.Hv.ConnectionServerHealth
CustomizationSpec                     : VMware.Hv.CustomizationSpec
Datacenter                            : VMware.Hv.Datacenter
Datastore                             : VMware.Hv.Datastore
DatastorePath                         : VMware.Hv.DatastorePath
Desktop                               : VMware.Hv.Desktop
DesktopHealth                         : VMware.Hv.DesktopHealth
DesktopTask                           : VMware.Hv.DesktopTask
DiagOperation                         : VMware.Hv.DiagOperation
EntitledUserOrGroup                   : VMware.Hv.EntitledUserOrGroup
EventDatabase                         : VMware.Hv.EventDatabase
EventDatabaseHealth                   : VMware.Hv.EventDatabaseHealth
Farm                                  : VMware.Hv.Farm
FarmHealth                            : VMware.Hv.FarmHealth
GSSAPIAuthenticator                   : VMware.Hv.GSSAPIAuthenticator
Gateway                               : VMware.Hv.Gateway
GatewayAccessUserOrGroup              : VMware.Hv.GatewayAccessUserOrGroup
GatewayHealth                         : VMware.Hv.GatewayHealth
GlobalAccessGroup                     : VMware.Hv.GlobalAccessGroup
GlobalApplicationEntitlement          : VMware.Hv.GlobalApplicationEntitlement
GlobalEntitlement                     : VMware.Hv.GlobalEntitlement
GlobalSessionQueryService             : VMware.Hv.GlobalSessionQueryService
GlobalSettings                        : VMware.Hv.GlobalSettings
HostOrCluster                         : VMware.Hv.HostOrCluster
ImageManagementAsset                  : VMware.Hv.ImageManagementAsset
ImageManagementStream                 : VMware.Hv.ImageManagementStream
ImageManagementTag                    : VMware.Hv.ImageManagementTag
ImageManagementVersion                : VMware.Hv.ImageManagementVersion
InstantCloneEngineDomainAdministrator : VMware.Hv.InstantCloneEngineDomainAdministrator
JwtToken                              : VMware.Hv.JwtToken
License                               : VMware.Hv.License
LogCollector                          : VMware.Hv.LogCollector
LogonTiming                           : VMware.Hv.LogonTiming
Machine                               : VMware.Hv.Machine
MessageClient                         : VMware.Hv.MessageClient
Monitoring                            : VMware.Hv.Monitoring
NetworkInterfaceCard                  : VMware.Hv.NetworkInterfaceCard
NetworkLabel                          : VMware.Hv.NetworkLabel
NetworkProxyConfiguration             : VMware.Hv.NetworkProxyConfiguration
Performance                           : VMware.Hv.Performance
Permission                            : VMware.Hv.Permission
PersistentDisk                        : VMware.Hv.PersistentDisk
PersistentDiskQueryService            : VMware.Hv.PersistentDiskQueryService
Pod                                   : VMware.Hv.Pod
PodAssignment                         : VMware.Hv.PodAssignment
PodEndpoint                           : VMware.Hv.PodEndpoint
PodFederation                         : VMware.Hv.PodFederation
PodHealth                             : VMware.Hv.PodHealth
Policies                              : VMware.Hv.Policies
Privilege                             : VMware.Hv.Privilege
QueryService                          : VMware.Hv.QueryService
RADIUSAuthenticator                   : VMware.Hv.RADIUSAuthenticator
RDSServer                             : VMware.Hv.RDSServer
RegisteredPhysicalMachine             : VMware.Hv.RegisteredPhysicalMachine
RemoteApplication                     : VMware.Hv.RemoteApplication
RemoteAssistantTicket                 : VMware.Hv.RemoteAssistantTicket
RemoteProcess                         : VMware.Hv.RemoteProcess
ResourcePool                          : VMware.Hv.ResourcePool
ResourceSettings                      : VMware.Hv.ResourceSettings
Role                                  : VMware.Hv.Role
SAMLAuthenticator                     : VMware.Hv.SAMLAuthenticator
SAMLAuthenticatorHealth               : VMware.Hv.SAMLAuthenticatorHealth
SecondaryCredentials                  : VMware.Hv.SecondaryCredentials
SecurityServer                        : VMware.Hv.SecurityServer
SecurityServerHealth                  : VMware.Hv.SecurityServerHealth
Session                               : VMware.Hv.Session
SessionStatistics                     : VMware.Hv.SessionStatistics
Site                                  : VMware.Hv.Site
SpaceReclamation                      : VMware.Hv.SpaceReclamation
StorageAccelerator                    : VMware.Hv.StorageAccelerator
StorageAcceleratorHost                : VMware.Hv.StorageAcceleratorHost
Syslog                                : VMware.Hv.Syslog
Task                                  : VMware.Hv.Task
URLRedirection                        : VMware.Hv.URLRedirection
UnauthenticatedAccessUser             : VMware.Hv.UnauthenticatedAccessUser
UsageStatistics                       : VMware.Hv.UsageStatistics
UserEntitlement                       : VMware.Hv.UserEntitlement
UserHomeSite                          : VMware.Hv.UserHomeSite
Validator                             : VMware.Hv.Validator
ViewClient                            : VMware.Hv.ViewClient
ViewComposerDomainAdministrator       : VMware.Hv.ViewComposerDomainAdministrator
ViewComposerHealth                    : VMware.Hv.ViewComposerHealth
VirtualCenter                         : VMware.Hv.VirtualCenter
VirtualCenterHealth                   : VMware.Hv.VirtualCenterHealth
VirtualCenterStatistics               : VMware.Hv.VirtualCenterStatistics
VirtualDisk                           : VMware.Hv.VirtualDisk
VirtualMachine                        : VMware.Hv.VirtualMachine
VirtualSAN                            : VMware.Hv.VirtualSAN
VmFolder                              : VMware.Hv.VmFolder
VmTemplate                            : VMware.Hv.VmTemplate
WS1Assist                             : VMware.Hv.WS1Assist

**Comment by imtrinity94** [comment]
What i really want is to perform **(Machine_Rebuild)** rebuild function on this object VMware.Hv.Machine for a desktop that I have in my full-clone desktop pool.

**Comment by bwuch** [comment]
Hello @imtrinity94 - the Connect-HvServer function is part of the PowerCLI module, however the Get-HVPool function comes from the VMware.Hv.Helper module.  If Connect-HvServer is working, but Get-HVPool is not, I'd verify that the VMware.Hv.Helper module is loaded.  You can find info on getting started with this module here: https://blogs.vmware.com/euc/2020/01/vmware-horizon-7-powercli.html and here: https://docs.vmware.com/en/VMware-Horizon-7/7.13/horizon-integration/GUID-B29EB217-30F0-4C58-9A49-95160392AA9C.html.  I hope this helps!

**Comment by imtrinity94** [comment]
Thanks a lot @bwuch & @freythman
