### ISSUE TITLE
[Vmware.Vsphere.SsoAdmin] Updating user passwords via SsoAdmin module 

### ISSUE THREAD

**Issue by thinkdavid** [vmware/PowerCLI-Example-Scripts#508]
Currently there is a cmdlet to update the certificate used to connect to an External AD source, but none to update the password. Many corporate customers have guidelines that mandate the rotation of passwords so this would be very useful to them.

**Comment by thinkdavid** [comment]
@dmilov

**Comment by dmilov** [comment]
@thinkdavid 
It's about the domain authentication password, isn't it? 
If we add a parameter set to `Set-LDAPIdentitySource` that updates the domain authentication would it cover the use-case?

**Comment by thinkdavid** [comment]
Yes, exactly. 
It's possible via the UI, I believe.

Updating the password as set by:
 [Parameter(
            Mandatory = $true,
            ValueFromPipeline = $false,
            ValueFromPipelineByPropertyName = $false,
            HelpMessage = 'Domain authentication password')]
        [ValidateNotNull()]
        [string]
        $Password,

**Comment by dmilov** [comment]
Fixed in https://www.powershellgallery.com/packages/VMware.vSphere.SsoAdmin/1.3.7
