### ISSUE TITLE
[VMware.vSphere.SsoAdmin] Issue with iterating through the certificates on the new version 1.3.6

### ISSUE THREAD

**Issue by thinkdavid** [vmware/PowerCLI-Example-Scripts#509]
This (non-terminating) error occurs when executing Get-IdentitySOurce -External

`An error occurred while enumerating through a collection: ASN1 corrupted data..`

I believe this is due to the new update.
https://github.com/dotnet/runtime/issues/54336 seems to support this issue.

**Comment by dmilov** [comment]
@thinkdavid Can you check the .NET Runtime version where this is reproduced?

**Comment by et1975** [comment]
The problem should be reproducible in a container based on mcr.microsoft.com/powershell:7.2.0-alpine-3.12-20211116

**Comment by et1975** [comment]
#590 Seems to narrow it down to Linux.

**Comment by et1975** [comment]
And https://github.com/dotnet/runtime/issues/15073#issuecomment-619422356 seems to be the culprit - signed cert are not loading correctly on Linux.
