### ISSUE TITLE
[VMware.vSphere.SsoAdmin] New-SsoPersonUser throws error 'One or more errors occurred'

### ISSUE THREAD

**Issue by GaryJBlake** [vmware/PowerCLI-Example-Scripts#519]
### Describe the bug

When attempting to add a user to the SSO Domain using New-SsoPersonUser it throws an error  'One or more errors occurred'.

New-SsoPersonUser -UserName TestAccount -Password VMw@re1! -Server $ssoConnectionDetails

New-SsoPersonUser : One or more errors occurred.
At line:1 char:1
+ New-SsoPersonUser -UserName TestAccount -Password VMw@re1! -Server $s ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-SsoPersonUser

### Reproduction steps

```bash
1. Connect to SSO Domain: $ssoConnectionDetails = Connect-SsoAdminServer -Server sfo-m01-vc01.sfo.rainpole.io -User administrator@vsphere.local -Password VMw@re1!
2. Issue new account creation: New-SsoPersonUser -UserName TestAccount -Password VMw@re1! -Server $ssoConnectionDetails

I've also tried without the -Server switch and a single SSO Server connected with the same outcome
```

### Expected behavior

Account should be created without an error

**Comment by dmilov** [comment]
Error handling in the module is not good enough here. The real server error after debugging with http proxy is
```
Failed: cannot create person user for user TestAccount because password policy is not satisfied
Caused by: Constraint violation
```

The fix should be to expose the server error details to the user.

**Comment by dmilov** [comment]
Version 1.3.8 on Windoiws PowerShell 7.0 works correct with the error handling:

```
> New-SsoPersonUser -UserName 'testuser' -Password 'd'
New-SsoPersonUser: One or more errors occurred. (The specified principal (testuser) is invalid.
Caused by: Another user or group already exists with the same name: accountName=testuser, principal=testuser@vsphere.local)
PS C:\Users\dmilov> New-SsoPersonUser -UserName 'testuser2' -Password 'd'
New-SsoPersonUser: One or more errors occurred. (Failed: cannot create person user for user testuser2 because password policy is not satisfied
Caused by: Constraint violation)
```

**Comment by dmilov** [comment]
1.3.8 is available on PS Gallery
