### ISSUE TITLE
Add new VI Property of KMSServer

### ISSUE THREAD

**Issue by mikefoley** [vmware/PowerCLI-Example-Scripts#52]
New-VIProperty -Name KMSserver -ObjectType VirtualMachine -Value {
        Param ($VM)
        if ($VM.Encrypted) {
          $vm.EncryptionKeyId.ProviderId.Id
        }
        } -BasedOnExtensionProperty 'Config.KeyId' -Force | Out-Null 

This outputs the KMS server that’s attached to the VM and replaces the code example I was thinking of using in my blog. 

    Get-VM |Select Name,KMSserver
 
    Name                                                          KMSserver                                                   
    ----                                                          ---------                                                   
    Windows10 -1                                                  KMS01                                                       
    Windows10                                                                                                                 
    PyKMIPServer

**Comment by BaoyinQiao** [comment]
It's a good idea, i'll put it in our current module ASAP.  Thanks, Mike.

Thanks,
Baoyin

**Comment by BaoyinQiao** [comment]
Mike, 

  The New property has been checked into our module, feel free to take a look. 

Thanks,
Baoyin
