### ISSUE TITLE
Error on Add-LDAPIdentitySource

### ISSUE THREAD

**Issue by yanlu2** [vmware/PowerCLI-Example-Scripts#533]
### Describe the bug

I'm trying to add AD over LDAPs to a vCenter but got error.
PS C:\Users\luy13> C:\PS_scripts\vCenter\vCenter-adding-AD-LDAPs.ps1

Press any key to continue add AD over LDAPs to vCenter rsaengbdvc1.rsa.lab.emc.com: 

Name        : server.corp.com
ServiceUri  : https://server.com/sso-adminserver/sdk/vsphere.local
User        : administrator@vsphere.local
Id          : /SsoAdminServer=vsphere.local/administrator@server.corp.com
IsConnected : True
Client      : VMware.vSphere.SsoAdminClient.SsoAdminClient
RefCount    : 3

Add-LDAPIdentitySource : Cannot process argument transformation on parameter 'Certificates'. Cannot convert value "cert.cer" to type 
"System.Security.Cryptography.X509Certificates.X509Certificate2[]". Error: "Cannot convert value "cert.cer" to type "System.Security.Cryptography.X509Certificates.X509Certificate2". 
Error: "The system cannot find the file specified.
""
At C:\PS_scripts\vCenter\vCenter-adding-AD-LDAPs.ps1:31 char:25
+           -Certificates 'cert.cer'
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-LDAPIdentitySource], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-LDAPIdentitySource
 
Disconnect-SsoAdminServer : Cannot process argument transformation on parameter 'Server'. Cannot convert the "server.corp.com" value of type "System.String" to type 
"VMware.vSphere.SsoAdminClient.DataTypes.SsoAdminServer[]".
At C:\PS_scripts\vCenter\vCenter-adding-AD-LDAPs.ps1:32 char:39
+     Disconnect-SsoAdminServer -Server $server
+                                       ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Disconnect-SsoAdminServer], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Disconnect-SsoAdminServer

### Reproduction steps

```bash
1. Run script vCenter-adding -AD-LDAPs.ps1
2. got error 
3. Script vCenter-adding -AD-LDAPs.ps1
$path="C:\Temp\Reports\vCenters\"                                                     # file location
$server="server.corp.comp.com"                                                 # VC server
$username = "administrator@vsphere.local"
$passwd = password
$localdomain="vsphere.local"
$corpdomain="corp.comp.com"
$vcenterfile=$path+"vcentertestlist.txt"
$vcenterlist = get-content $vcenterfile


Foreach ($server in $vcenterlist) {
    $hostname=$server.Split(".")[0] 
    $rptfile=$path+"usrimpt-"+$hostname+".txt"

#    Read-Host -Prompt "`nPress any key to continue add AD over LDAPs to vCenter $server"

    Connect-SsoAdminServer -Server $server -User $username -Password $passwd -SkipCertificateCheck

    #Get-IdentitySource -External
    Add-LDAPIdentitySource `
          -Name 'Corp LDAPs' `
          -DomainName 'corp.comp.com' `
          -DomainAlias 'Corp' `
          -PrimaryUrl 'ldaps://appauth.corp.comp.com:636' `
          -BaseDNUsers 'dc=corp,dc=comp,dc=com' `
          -BaseDNGroups 'dc=corp,dc=comp,dc=com' `
          -Username 'svc_vmlabmgr@corp.comp.com' `
          -Password 'adfadfdaadfadf' `
          -Certificates 'cert.cer'
    Disconnect-SsoAdminServer -Server $server
}
4. output
PS C:\Users\luy13> C:\PS_scripts\vCenter\vCenter-adding-AD-LDAPs.ps1


Name        : server.corp.comp.com
ServiceUri  : https://server.corp.comp.com/sso-adminserver/sdk/vsphere.local
User        : administrator@vsphere.local
Id          : /SsoAdminServer=vsphere.local/administrator@server.corp.comp.com
IsConnected : True
Client      : VMware.vSphere.SsoAdminClient.SsoAdminClient
RefCount    : 5

Add-LDAPIdentitySource : Cannot process argument transformation on parameter 'Certificates'. Cannot convert value "cert.cer" to type 
"System.Security.Cryptography.X509Certificates.X509Certificate2[]". Error: "Cannot convert value "cert.cer" to type "System.Security.Cryptography.X509Certificates.X509Certificate2". 
Error: "The system cannot find the file specified.
""
At C:\PS_scripts\vCenter\vCenter-adding-AD-LDAPs.ps1:29 char:25
+           -Certificates 'cert.cer'
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-LDAPIdentitySource], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-LDAPIdentitySource
 
Disconnect-SsoAdminServer : Cannot process argument transformation on parameter 'Server'. Cannot convert the "server.corp.comp.com" value of type "System.String" to type 
"VMware.vSphere.SsoAdminClient.DataTypes.SsoAdminServer[]".
At C:\PS_scripts\vCenter\vCenter-adding-AD-LDAPs.ps1:30 char:39
+     Disconnect-SsoAdminServer -Server $server
+                                       ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Disconnect-SsoAdminServer], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Disconnect-SsoAdminServer
```

### Expected behavior

add AD over ldaps to vCenter

**Comment by yanlu2** [comment]
something worng in my script.

**Comment by dmilov** [comment]
Issue 1: `cert.cer` should be relative or absolute path to the `cer` file. If it is in the script working directory try `./cert.cer`

Issue 2: `$server` variable is string type, passing it as an argument to `Disconnect-SsoAdminServer` won't work because this module is missing the PowerCLI OBN (resolving object by name) feature.

Suggestion to fix the script:

```powershell
Foreach ($server in $vcenterlist) {
    $hostname=$server.Split(".")[0] 
    $rptfile=$path+"usrimpt-"+$hostname+".txt"

#    Read-Host -Prompt "`nPress any key to continue add AD over LDAPs to vCenter $server"

    $serverConnection = Connect-SsoAdminServer -Server $server -User $username -Password $passwd -SkipCertificateCheck

    #Get-IdentitySource -External
    Add-LDAPIdentitySource `
          -Name 'Corp LDAPs' `
          -DomainName 'corp.comp.com' `
          -DomainAlias 'Corp' `
          -PrimaryUrl 'ldaps://appauth.corp.comp.com:636' `
          -BaseDNUsers 'dc=corp,dc=comp,dc=com' `
          -BaseDNGroups 'dc=corp,dc=comp,dc=com' `
          -Username 'svc_vmlabmgr@corp.comp.com' `
          -Password 'adfadfdaadfadf' `
          -Certificates './cert.cer'

    Disconnect-SsoAdminServer -Server $serverConnection
}
```



In order to fix the second issue change the code to

**Comment by yanlu2** [comment]
Thanks, it works.


Regards,
-Yan



Internal Use - Confidential
