### ISSUE TITLE
Import-CIVAppTemplate fails

### ISSUE THREAD

**Issue by ibeerens** [vmware/PowerCLI-Example-Scripts#624]
### Describe the bug

When using the Import-CIVAppTemplate command to import an OVF file in a catalog for vCloud Director the following error is thrown:
Exception of type 'VMware.VimAutomation.Cloud.Views.Http.HttpUnsuccessfulRequestException' was thrown.

The percentage complete progress indicator is running and after some time the error is displayed.

Tried different versions of PowerCLI including the latest (VMware.PowerCLI 13.2.0 build 22746353). This makes no difference.

### Reproduction steps

1. Authenticate to VCD with a token
2. Run the following command:
3. Import-CIVAppTemplate -SourcePath <ovf_path> -Name <srv2022dccore> -Catalog <catalog_name> 

### Expected behavior

The upload of the OVF file is succesfull

**Comment by kamennikolov** [comment]
VMware PowerCLI is not open-source and is not part of this repo. This repo is only for sample scripts and community modules. All PowerCLI issues should be reported via the official VMware channels by filing an SR as described here: https://developer.vmware.com/docs/15315/GUID-0F835722-E667-4177-A8EF-51AB15FA837E.html.
