### ISSUE TITLE
VCHA.psm1 Enhancement

### ISSUE THREAD

**Issue by dstamen** [vmware/PowerCLI-Example-Scripts#64]
Can you please add a module for Set-VCHAMaintenance $true/$false/etc to be able to use powercli module to put a VCHA cluster into maintenance?

**Comment by lamw** [comment]
Does this not already exists with [Set-VCSAClusterMode](https://github.com/vmware/PowerCLI-Example-Scripts/blob/master/Modules/VCHA.psm1#L95)?

**Comment by dstamen** [comment]
It does :)
