### ISSUE TITLE
User Entitlement to the pool for New-HVpool

### ISSUE THREAD

**Issue by ajaynadadakuditi** [vmware/PowerCLI-Example-Scripts#68]
Hi,

I am using New-HVPool function to create a manual pool. Pool is created successfully, but how do I provide user Entitlement to the pool? I see there is a parameter named 'GlobalEntitlement', but I dont think it has been used anywhere in the function. Can you please let me know how we can add an user to the pool either using the same New-HVPool function or through any other function?

**Comment by mtelvers** [comment]
Hi, Once you have created your pool with New-HVPool, add an entitlement with New-HVEntitlement, thus:

`New-HVEntitlement -User domain\username -ResourceName $pool -Type User -HvServer $vcs`

Regards

Mark

**Comment by bro4856** [comment]
Any idea how to add group to pool. User gets added successfully via below.
New-HVEntitlement   -User arun@arundev.me -ResourceName mypool

**Comment by freythman** [comment]
To entitle a group, you need to include the `-Type` parameter, specified as `Group` such as this:

`New-HVEntitlement -User domain\group -ResourceName 'poolname' -Type Group`

The nomenclature of `-User` might seem confusing but that is used to specify the name of the user or group that you are entitling.

**Comment by freythman** [comment]
@ajaynadadakuditi Can you close this issue, since it seems resolved now?
