### ISSUE TITLE
get-hvmachine on empty pool exits all scripts

### ISSUE THREAD

**Issue by Magneet** [vmware/PowerCLI-Example-Scripts#74]
I have a simple script like this (modules are already loaded) that I am using as a base to catch all vdi desktops based on a different then the default snapshot

```
$pools=(get-hvpool)
write-output "All pools"
$pools.base.name
foreach ($pool in $pools){
$poolname=$pool.base.name
if ($pool.type -like "*automated*"){
write-output "Checking pool:"
$poolname
$poolmachines=get-hvmachine ($pool.base.name)
$wrongsnap=$poolmachines | where {$_.managedmachinedata.viewcomposerdata.baseimagesnapshotpath -notlike  $pool.automateddesktopdata.VirtualCenternamesdata.snapshotpath}
write-output "Desktops based on wrong snapshot:"
$wrongsnap.base.name
}
}

```
This scripts gives a nice message for empty pools: 

> VDI_Pool95

> No Virtual Machine(s) Found with given search parameters

But the script halts with this after any pool that doesn't contain any desktops. I have attached a screenshot of the output:
![2017-04-19 10_21_5](https://cloud.githubusercontent.com/assets/27762574/25170272/38a136f2-24ea-11e7-8254-8d0180a3244e.png)
(VDI_Pool99 actually contains a desktop based on a different snapshot)

**Comment by Magneet** [comment]
commenting out the break on line 5141 seems to fix this.

**Comment by StuebiSoft** [comment]
The removed brake is back again in the code. I think it was readd with a merge of a huge change at 17 May 2017.
