### ISSUE TITLE
Set-HVPool key and value

### ISSUE THREAD

**Issue by skonvols2k** [vmware/PowerCLI-Example-Scripts#83]
Hi,
I'm trying to automate my new pool creation with the following:

First clone and disable the pool (this code is working):
`Get-HVPool -PoolName 'Test' | New-HVPool -PoolName $name -NamingPattern "$short-{n:fixed=3}"
Set-HVPool  -PoolName $name -Disable`

Then I need to change keys maxNumberOfMachines and ResourcePool, i'm using this:
`Set-HVPool  -PoolName $name -key 'AutomatedDesktopSpec.VmNamingSpec.patternNamingSettings.maxNumberOfMachines' -value $maxvdi
Set-HVPool  -PoolName $name -key 'AutomatedDesktopSpec.VirtualCenterProvisioningSettings.VirtualCenterProvisioningData.ResourcePool' -value $short`

but have this error:
```
Exception calling "Desktop_Update" with "3" argument(s): "ExceptionType : VMware.Hv.InvalidArgument
ErrorMessage : Invalid member name.
ParameterName : AutomatedDesktopSpec.VmNamingSpec.patternNamingSettings.maxNumberOfMachines"
At C:\Program Files\WindowsPowerShell\Modules\VMware.Hv.Helper\VMware.HV.Helper.psm1:4329
char:7
       $desktop_helper.Desktop_Update($services,$item,$updates)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId : VimException
```

Can someone please help me?
Thanks

**Comment by mtelvers** [comment]
Hi, the key values you are using do not appear to be correct.  It should be automatedDesktopData.  Try something like this:

`Set-HVPool -PoolName $name -key 'automatedDesktopData.vmNamingSettings.patternNamingSettings.maxNumberOfMachines' -value 6`

For Set-HVPool, the property names are for the DesktopInfo data object in the API reference.  AutomatedDesktopSpec is used for New-HVPool

Regards

Mark

**Comment by rpstester** [comment]
Case matters, @skonvols2k ; I was stuck like you until I realized that I had to start each one with a lowercase letter as @mtelvers has demonstrated.

**Comment by skonvols2k** [comment]
Hi,
thanks both of you.

can you help me please more with automatedDesktopData.virtualCenterProvisioningSettings.virtualCenterProvisioningData.resourcePool it want a data object ResourcePoolId of class VMware.Hv.ResourcePoolId how i can get this id having resourcepool name?

it doesn't match with (get-resourcepool).id from vsphere api

Thanks

**Comment by mtelvers** [comment]
@skonvols2k You need to use the API call `ResourcePool_GetResourcePoolTree()` to get the resource pool tree structure which you would then need to search recursively to find the ID which matches the name you were looking for.  It's not easy as you first need to find the ID for the Host/Cluster that the resource pool is in which is requires a datacenter ID...

Can you give me more or an overview of what you are trying to do and perhaps I can suggest away around it?

**Comment by skonvols2k** [comment]
@mtelvers as you can see in first post, i'm used to create a new pool cloning an existing one, the only thins that i need to change is the name and namingPattern, the maxNumberOfMachines and the resource pool in which running those vdis. My complete script is:

`Import-Module VMware.VimAutomation.HorizonView
Import-Module VMware.VimAutomation.Core

$name="TestMigr"
$short="TestMigr"
$maxvdi="2"

Connect-HVServer conn-serv -Credential (get-credential xxx\xxx)
Connect-VIServer vdi-vcenter -Credential (get-credential xxx\xxx)
New-ResourcePool -Location (Get-Cluster -Name VDI) -Name $short -CpuExpandableReservation $true -CpuReservationMhz 0 -CpuSharesLevel Normal -MemExpandableReservation $true -MemReservationMB 0 -MemSharesLevel Normal
Disconnect-VIServer rm-vc-vdi.int.gamenet.it -confirm:$false

Get-HVPool -PoolName 'Test' | New-HVPool -PoolName $name -NamingPattern "$short-{n:fixed=3}"

Set-HVPool  -PoolName $name -Disable

Set-HVPool  -PoolName $name -key 'automatedDesktopData.vmNamingSettings.patternNamingSettings.maxNumberOfMachines' -value $maxvdi
Set-HVPool  -PoolName $name -key 'automatedDesktopData.virtualCenterProvisioningSettings.virtualCenterProvisioningData.resourcePool' -value $short`

Of course last line is not working because $short is the name of the resourcepool not the ResourcePoolId

Thanks

**Comment by skonvols2k** [comment]
Trying with:
`New-HVPool -PoolName $name -NamingPattern "$short-{n:fixed=3}" -resourcePool $short`

get as result:

```
New-HVPool : Parameter set cannot be resolved using the specified named parameters.
At C:\Users\m.sommella.admin\Desktop\Scripts\desktop_pool.ps1:16 char:31
+ Get-HVPool -PoolName 'Test' | New-HVPool -PoolName $name -NamingPattern "$short- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HVPool], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,New-HVPool
```

**Comment by mtelvers** [comment]
"Parameter set cannot be resolved using the specified named parameters" is PowerShell rejecting the command line as the cmdlet is configured with parameter groups so you'd additionally need to add all the -LinkedClone parameters.

I've written some code to do what you want in PR #139 

`Set-HVPool -Poolname test -ResourcePool NewRP`

**Comment by skonvols2k** [comment]
Hi,
sorry for late response, tested and working!
Thanks
