### ISSUE TITLE
Connect-HVserver provides cert issue

### ISSUE THREAD

**Issue by gaborus** [vmware/PowerCLI-Example-Scripts#95]
Using powercli 6.5 I cannot connect against a Horizon 6.0.1
However script works against 6.2.1

Seems like a cert issue, but cannot fix it. Anybody with an idea?

######################Script###################
$hostvar = $args[0]
$hzUser = $args[1]
$hzPass = $args[2]
$hzDomain = $args[3]
#Import-Module VMware.VimAutomation.Sdk
Import-Module VMware.VimAutomation.HorizonView
$hvServer = Connect-HVServer -server $hostvar -User $hzUser -Password $hzPass -Domain $hzDomain

####################Error####################

Connect-HVServer : Could not establish secure channel for SSL/TLS with authority 'xxxxxx'

**Comment by freythman** [comment]
You will need to upgrade the Horizon 6.0.1 environment in order to use PowerCLI 6.5+

You can see the versions of Horizon that are compatible with PowerCLI here: https://www.vmware.com/resources/compatibility/sim/interop_matrix.php#interop&299=1669&0=
